image: python:3.5

before_script:
  - pip install poetry==1.0b2
  - poetry config virtualenvs.create false
  - poetry install --no-root
  - export PYTHONPATH="$PWD/src"

tests:
  stage: test
  script:
    - ./run_tests.sh

code_analysis:
  stage: test
  script:
    - ./pylint.sh
    - ./check-crlf.sh
